/* ═════════════════════════════════════════════════════════════════
   THE MINUTE — 15 stories for today's edition.
   Each summary is ~45-60 words, ~30 seconds to read aloud.
═════════════════════════════════════════════════════════════════ */

export interface MinuteStory {
  id:            string;
  category:      string;
  categoryColor: string;   // primary brand color for this story
  categoryTint:  string;   // very light wash for backgrounds
  headline:      string;
  summary:       string;
  source:        string;
  timeAgo:       string;
  readSeconds:   number;
  image:         string;   // Unsplash CDN URL
  imageAlt:      string;
}

export const MINUTE_STORIES: MinuteStory[] = [
  {
    id:            'india-3rd-economy',
    category:      'ECONOMY',
    categoryColor: '#a03a20',
    categoryTint:  '#fde8df',
    headline:      "India overtakes Japan to become world's third-largest economy",
    summary:       "India's nominal GDP crossed $4.5 trillion this quarter, formally surpassing Japan and trailing only the US and China. The transition was anticipated by IMF projections released last year. Analysts cite robust manufacturing growth, a record services trade surplus, and population dividend as the underlying drivers.",
    source:        'Reuters',
    timeAgo:       '2h ago',
    readSeconds:   30,
    image:         'https://loremflickr.com/1400/788/economy,mumbai,india?lock=1',
    imageAlt:      'Mumbai skyline at dusk',
  },
  {
    id:            'openai-court-ruling',
    category:      'TECHNOLOGY',
    categoryColor: '#5b21b6',
    categoryTint:  '#ede7fa',
    headline:      'OpenAI loses landmark New York Times copyright case',
    summary:       'A federal judge ruled OpenAI infringed NYT articles during training of GPT models. Damages exceed $1.8 billion in actual losses plus statutory penalties. The decision sets the first major US precedent for training-data liability and is expected to reshape AI licensing across the industry.',
    source:        'Wall Street Journal',
    timeAgo:       '4h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/court,judge,gavel?lock=1',
    imageAlt:      'Circuit board patterns',
  },
  {
    id:            'arctic-sea-ice',
    category:      'CLIMATE',
    categoryColor: '#0e7490',
    categoryTint:  '#dcf2f5',
    headline:      'Arctic sea ice hits lowest May extent since 1979 records began',
    summary:       'Satellite data confirms Arctic sea ice coverage fell to 11.2 million km² this month, 18% below the 1981–2010 average. Researchers attribute the loss to a persistent marine heatwave in the Barents Sea. The shift threatens early disruption to polar shipping routes and northern ecosystems.',
    source:        'BBC',
    timeAgo:       '5h ago',
    readSeconds:   30,
    image:         'https://loremflickr.com/1400/788/arctic,ice,sea?lock=1',
    imageAlt:      'Sea ice floating in arctic waters',
  },
  {
    id:            'h1b-visa-review',
    category:      'POLITICS',
    categoryColor: '#7f1d1d',
    categoryTint:  '#fae0e0',
    headline:      'White House extends H-1B visa review period to 90 days',
    summary:       'A new executive order lengthens the H-1B specialty-occupation visa review window from 30 to 90 days, citing fraud-screening upgrades. Tech employers warn the change could delay 200,000 work-authorization renewals this fiscal year. Trade groups have signaled possible legal challenges within weeks.',
    source:        'Politico',
    timeAgo:       '6h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/visa,passport,immigration?lock=1',
    imageAlt:      'US Capitol Building at golden hour',
  },
  {
    id:            'nifty-record',
    category:      'MARKETS',
    categoryColor: '#065f46',
    categoryTint:  '#d8eee5',
    headline:      'Nifty 50 closes above 28,000 for the first time on FII buying',
    summary:       "India's benchmark Nifty 50 added 1.4% to settle at 28,162, breaching the historic threshold. Foreign institutional investors purchased ₹9,200 crore of equities net, the highest single-day inflow this year. Banking, IT, and capital-goods sectors led the rally on cooler-than-expected April inflation.",
    source:        'Bloomberg',
    timeAgo:       '7h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/stockmarket,trading,bombay?lock=1',
    imageAlt:      'Stock market chart on screen',
  },
  {
    id:            'spacex-mars-mission',
    category:      'SCIENCE',
    categoryColor: '#312e81',
    categoryTint:  '#e1e0f4',
    headline:      'SpaceX confirms uncrewed Mars cargo mission launches November',
    summary:       'SpaceX has finalized the November 2026 launch window for its first uncrewed Starship cargo mission to Mars. The vehicle will deliver 100 tonnes of supplies and a habitat module to Jezero Crater. A successful demo is the gating step for crewed Mars flight planned for 2028.',
    source:        'Ars Technica',
    timeAgo:       '8h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/rocket,space,launch?lock=1',
    imageAlt:      'Rocket launch trail against sky',
  },
  {
    id:            'csk-ipl-win',
    category:      'SPORTS',
    categoryColor: '#c2410c',
    categoryTint:  '#fde4d6',
    headline:      'Chennai Super Kings clinch sixth IPL title in last-ball thriller',
    summary:       "CSK beat Mumbai Indians by 4 runs in last night's IPL 2026 final at Narendra Modi Stadium, sealing a sixth championship. Dhoni, playing his farewell season at 44, scored 38 from 16 balls. The win extends CSK's record as the league's most successful franchise across 19 seasons.",
    source:        'ESPNcricinfo',
    timeAgo:       '10h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/cricket,stadium,india?lock=1',
    imageAlt:      'Floodlit cricket stadium',
  },
  {
    id:            'alzheimer-pill',
    category:      'HEALTH',
    categoryColor: '#9f1239',
    categoryTint:  '#fbdee5',
    headline:      "First oral Alzheimer's pill clears Phase III with 47% slowdown",
    summary:       "Eli Lilly's daily oral tablet, donanemab-OR, slowed cognitive decline by 47% over 18 months in a 3,400-patient Phase III trial. Unlike existing infusions, the pill can be self-administered at home. FDA filing is targeted for July 2026, potentially the first at-home disease-modifying treatment.",
    source:        'NEJM',
    timeAgo:       '12h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/medicine,pill,pharmacy?lock=1',
    imageAlt:      'Pharmaceutical pills on white surface',
  },
  {
    id:            'oscars-2027-date',
    category:      'CULTURE',
    categoryColor: '#92400e',
    categoryTint:  '#fbe5cf',
    headline:      'Academy moves Oscars 2027 to January, shortest gap in history',
    summary:       'The Academy of Motion Picture Arts announced the 99th Oscars will air January 24, 2027, shortening the eligibility gap from the previous March ceremony. The shift aligns with streaming-era release cadences and an expanded International Feature field that now includes 24 submissions, a record.',
    source:        'Variety',
    timeAgo:       '14h ago',
    readSeconds:   30,
    image:         'https://loremflickr.com/1400/788/cinema,oscars,redcarpet?lock=1',
    imageAlt:      'Cinema spotlight on red curtain',
  },
  {
    id:            'taiwan-strait-incident',
    category:      'WORLD',
    categoryColor: '#1e3a8a',
    categoryTint:  '#dde3f4',
    headline:      'Taiwan reports 24 PLA warplanes crossed median line overnight',
    summary:       "Taiwan's Ministry of National Defense said 24 Chinese aircraft, including J-16 fighters and KJ-500 radar planes, crossed the Taiwan Strait median line between 11 PM and 4 AM local time. It marks the largest single-night incursion this quarter. Taipei scrambled F-16Vs in response; no contact reported.",
    source:        'Al Jazeera',
    timeAgo:       '15h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/fighter,aircraft,jet?lock=1',
    imageAlt:      'Fighter jets in formation against sky',
  },
  {
    id:            'tata-chip-fab',
    category:      'BUSINESS',
    categoryColor: '#047857',
    categoryTint:  '#daefe2',
    headline:      "Tata's Gujarat chip fab ships first 28nm wafers ahead of schedule",
    summary:       "Tata Electronics' $11 billion Dholera fabrication plant produced its first commercial 28-nanometer wafers six months ahead of plan. Initial output is destined for automotive and industrial customers. The milestone makes India only the seventh nation with operational large-scale logic chip production capacity.",
    source:        'Mint',
    timeAgo:       '16h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/semiconductor,chip,factory?lock=1',
    imageAlt:      'Semiconductor wafer surface',
  },
  {
    id:            'apple-ai-search',
    category:      'TECHNOLOGY',
    categoryColor: '#5b21b6',
    categoryTint:  '#ede7fa',
    headline:      'Apple unveils on-device AI search; Google deal renegotiated',
    summary:       'At WWDC 2026, Apple introduced an on-device generative AI search layer for iOS 19 and macOS 16, replacing Google as default for short factual queries. The Google search-revenue partnership, reportedly worth $20 billion per year, has been restructured to a per-query payment model effective September.',
    source:        'The Verge',
    timeAgo:       '18h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/apple,iphone,technology?lock=1',
    imageAlt:      'Apple devices on minimal desk',
  },
  {
    id:            'eu-defense-bond',
    category:      'WORLD',
    categoryColor: '#1e3a8a',
    categoryTint:  '#dde3f4',
    headline:      'EU finance ministers approve €150 billion joint defense bond',
    summary:       "European Union finance ministers unanimously approved a €150 billion joint defense bond at this morning's ECOFIN meeting. Funds will purchase air-defense systems and standardize munitions across member states. It is the largest joint debt instrument since the pandemic-era NextGenerationEU package of 2020.",
    source:        'Financial Times',
    timeAgo:       '19h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/europe,parliament,brussels?lock=1',
    imageAlt:      'European Union flag in front of architecture',
  },
  {
    id:            'solar-grid-india',
    category:      'CLIMATE',
    categoryColor: '#0e7490',
    categoryTint:  '#dcf2f5',
    headline:      'India crosses 200 GW of installed renewable energy capacity',
    summary:       "India's installed renewable energy capacity crossed 200 gigawatts this morning, hitting a national clean-energy milestone. Solar leads at 112 GW, followed by wind at 48 GW. The country remains on track for its 500 GW non-fossil target by 2030. Rooftop solar additions led monthly growth.",
    source:        'PIB India',
    timeAgo:       '20h ago',
    readSeconds:   30,
    image:         'https://loremflickr.com/1400/788/solar,panel,renewable?lock=1',
    imageAlt:      'Solar panel array under blue sky',
  },
  {
    id:            'btc-150k',
    category:      'MARKETS',
    categoryColor: '#065f46',
    categoryTint:  '#d8eee5',
    headline:      'Bitcoin breaches $150,000 amid record US ETF inflows',
    summary:       "Bitcoin crossed $150,000 for the first time, gaining 6.2% in 24 hours. US spot Bitcoin ETFs recorded $2.1 billion of net inflows yesterday, the second-highest single-day on record. Coinbase reported transient outage during peak trading. The total crypto market cap now exceeds $4.8 trillion.",
    source:        'CoinDesk',
    timeAgo:       '22h ago',
    readSeconds:   32,
    image:         'https://loremflickr.com/1400/788/bitcoin,cryptocurrency,coin?lock=1',
    imageAlt:      'Abstract cryptocurrency pattern',
  },
];

export const TOTAL_READ_SECONDS = MINUTE_STORIES.reduce((s, x) => s + x.readSeconds, 0);
